spring.application.name=DentalCloudBackend

# --- Configuración de DataSource para PostgreSQL ---

# 1. Driver de la base de datos
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. URL de la conexión
# Como mapeaste el puerto 5432 del contenedor al puerto 5432 de tu máquina (localhost),
# esta es la URL correcta:
spring.datasource.url=jdbc:postgresql://localhost:5432/DentalCloudDB

# 3. Usuario de la base de datos
spring.datasource.username=DentalAdmin

# 4. Contraseña de la base de datos
spring.datasource.password=Deathofadream

# --- Configuración Opcional de Hibernate/JPA ---
# Esto es muy recomendable para el desarrollo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
