spring:
  application:
    name: DentalCloudBackend
  datasource:
    # Usaremos las variables de entorno para que Docker Compose las inyecte
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    # Configuraciones de Hibernate
    hibernate:
      ddl-auto: update # Muy útil en desarrollo
    show-sql: true
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:1296000000}